# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: danieltesting
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: whitehaven
# "service" is the name of this project. This will also be added to your AWS resource names.
service: whitehaven

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage}
  region: ap-southeast-2
  stackName: whiteheaven-stack-${self:provider.stage}
  deploymentMethod: direct
  disableRollback: false

  iam:
    role:
      name: whiteheaven-lambda-task-role
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
          Resource: "*"

  environment:
    MEMBERS_TABLE: ${env:MEMBERS_TABLE}
    CONTRACTS_TABLE: ${env:CONTRACTS_TABLE}
    PROSPECTS_TABLE: ${env:PROSPECTS_TABLE}
    WEBHOOK_MEMBER_URL: ${env:WEBHOOK_MEMBER_URL}
    WEBHOOK_PROSPECT_URL: ${env:WEBHOOK_PROSPECT_URL}
    AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}
    ENV: ${self:provider.stage}

  deploymentBucket:
    name: whiteheaven-deployment-bucket-${self:provider.stage}
    blockPublicAccess: true
    serverSideEncryption: AES256
    versioning: true
    maxPreviousDeploymentArtifacts: 3

functions:
  memberChangeHandler:
    handler: src/index.handler
    events:
      - sqs:
          arn: arn:aws:sqs:ap-southeast-2:${env:AWS_ACCOUNT_ID}:whiteheaven_member_change_${self:provider.stage}.fifo
          maximumConcurrency: 200
          batchSize: 3

custom:
  prune:
    automatic: true
    includeLayers: true
    number: 3

plugins:
  - serverless-prune-plugin
