const memberEventType = Object.freeze({
  MEMBER_JOINED: "MEMBER_JOINED",
  MEMBER_BLOCKED: "MEMBER_BLOCKED",
  MEMBER_UNBLOCKED: "MEMBER_UNBLOCKED",
  MEMBER_OVERDUE: "MEMBER_OVERDUE",
  MEMBER_PROSPECT: "MEMBER_PROSPECT",
  CANCELLATION_CREATED: "CANCELLATION_CREATED",
  CANCELLATION_REVOKED: "CANCELLATION_REVOKED"
});

export { memberEventType };
