const memberEventType = Object.freeze({
  MEMBER_JOINED: "MEMBER_JOINED",
  MEMBER_BLOCKED: "MEMBER_BLOCKED",
  MEMBER_UNBLOCKED: "MEMBER_UNBLOCKED",
  MEMBER_OVERDUE: "MEMBER_OVERDUE",
  MEMBER_PROSPECT: "MEMBER_PROSPECT",
  CANCELLATION_CREATED: "CANCELLATION_CREATED",
  CANCELLATION_REVOKED: "CANCELLATION_REVOKED",
  SUSPENSION_CREATED: "SUSPENSION_CREATED",
  SUSPENSION_UPDATED: "SUSPENSION_UPDATED",
  SUSPENSION_REVOKED: "SUSPENSION_REVOKED",
  MEMBER_SUSPENDED: "MEMBER_SUSPENDED",
  MEMBER_CANCELLED: "MEMBER_CANCELLED",
  SUSPENSION_MEDICAL_CREATED: "SUSPENSION_MEDICAL_CREATED",
  SUSPENSION_MEDICAL_CANCELLED: "SUSPENSION_MEDICAL_CANCELLED",
  SUSPENSION_MEDICAL_UPDATED: "SUSPENSION_MEDICAL_UPDATED",
  SUSPENSION_MEDICAL_REVOKED: "SUSPENSION_MEDICAL_REVOKED",
  SUSPENSION_MEDICAL_APPROVED: "SUSPENSION_MEDICAL_APPROVED"
});

export { memberEventType };
