name: Deploy - dev

on:
  pull_request:
    branches:
      - main
    types:
      - review_requested
      - ready_for_review
      - assigned

permissions:
  id-token: write
  contents: read

jobs:
  deploy_to_dev:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      aws_region: ap-southeast-2
      branch: ${{ github.event.pull_request.head.ref }}
    secrets: inherit
