name: Deploy - prod

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy_to_dev:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      aws_region: ap-southeast-2
      branch: main
    secrets: inherit

  deploy_to_prod:
    uses: ./.github/workflows/deploy.yml
    needs: deploy_to_dev
    with:
      environment: prod
      aws_region: ap-southeast-1
      branch: main
    secrets: inherit
