name: Deploy Pipeline

on:
  push:
    branches: ["main"]

jobs:
  run_tests:
    uses: ./.github/workflows/lint_test.yml
    with:
      ref: ${{ github.ref_name }}

  deploy_to_dev:
    needs: run_tests
    # Enable when required.
    if: false
    uses: ./.github/workflows/deploy.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: dev
      aws_region: ap-southeast-2
      ref: ${{ github.ref_name }}
    secrets: inherit

  deploy_to_prod:
    needs: deploy_to_dev
    # Enable when required
    if: false
    uses: ./.github/workflows/deploy.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: prod
      aws_region: ap-southeast-2
      ref: ${{ github.ref_name }}
    secrets: inherit
