name: Deploy Lambda

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: string
      aws_region:
        description: "AWS region"
        required: true
        type: string
      branch:
        description: "The branch to deploy"
        required: true
        type: string

jobs:
  deploy:
    name: Deploy - ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Install Serverless
        run: npm install -g serverless

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws_region }}
          role-to-assume: ${{ secrets.AWS_STS_ROLE }}

      - name: Deploy Lambda
        run: serverless deploy --stage ${{ inputs.environment }}
        env:
          MEMBERS_TABLE: ${{ vars.MEMBERS_TABLE }}
          CONTRACTS_TABLE: ${{ vars.CONTRACTS_TABLE }}
          PROSPECTS_TABLE: ${{ vars.PROSPECTS_TABLE }}
          WEBHOOK_MEMBER_URL: ${{ vars.WEBHOOK_MEMBER_URL }}
          WEBHOOK_PROSPECT_URL: ${{ vars.WEBHOOK_PROSPECT_URL }}
          AWS_REGION: ${{ inputs.aws_region }}
          SQS_ARN: ${{ vars.SQS_ARN }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

      - name: Cleanup
        run: serverless remove --stage ${{ inputs.environment }}
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_REGION: ${{ inputs.aws_region }}
