name: Deploy - prod

on:
  push:
    branches:
      - main

jobs:
  deploy_to_dev:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      aws_region: ap-southeast-2
      branch: main
      member_table: "Member-jyq7cvj6s5cw3dpsd6pvprmfbu-amritnew"
      contract_table: "MemberContract-jyq7cvj6s5cw3dpsd6pvprmfbu-amritnew"
      suspension_table: "MemberContractSuspension-jyq7cvj6s5cw3dpsd6pvprmfbu-amritnew"
      prospect_table: "Prospect-jyq7cvj6s5cw3dpsd6pvprmfbu-amritnew"
      webhook_member_url: ""
      webhook_prospect_url: ""
    secrets: inherit

  deploy_to_prod:
    uses: ./.github/workflows/deploy.yml
    needs: deploy_to_dev
    with:
      environment: prod
      aws_region: ap-southeast-2
      branch: main
    secrets: inherit
